# Generated by Django 6.0 on 2026-01-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delai_max',
            field=models.PositiveIntegerField(default=3, help_text='Jours max'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delai_min',
            field=models.PositiveIntegerField(default=1, help_text='Jours min'),
        ),
    ]
