# Generated by Django 6.0 on 2026-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_order_key_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat (Coût)"),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
