# Generated by Django 6.0 on 2026-01-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_prix_achat_alter_order_order_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fiche_technique',
            field=models.TextField(blank=True),
        ),
    ]
